spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:im_platform_open}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

minio:
  endpoint: http://127.0.0.1:9000 #内网地址
  domain: http://${MINIO_DOMAIN:localhost}:9000  #外网访问地址（本机测试用localhost，多设备用IP）
  accessKey: admin
  secretKey: admin123456
  bucketName: tyut-chat
  imagePath: image
  filePath: file
  videoPath: video
  expireIn: 180 # 文件过期时间,单位:天

webrtc:
  max-channel: 9 # 多人通话最大通道数量，最大不能超过16,建议值:4,9,16
  iceServers:
    - urls: stun:stun.l.google.com:19302


